// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sample_use_proxy.Data;

namespace sample_use_proxy.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20200101035029_WeatherMigration")]
    partial class WeatherMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sample_use_proxy.Data.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Forecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2020, 1, 1, 22, 50, 29, 357, DateTimeKind.Local).AddTicks(2261),
                            Summary = "Bracing",
                            TemperatureC = 2
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2020, 1, 2, 22, 50, 29, 359, DateTimeKind.Local).AddTicks(2129),
                            Summary = "Warm",
                            TemperatureC = 35
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2020, 1, 3, 22, 50, 29, 359, DateTimeKind.Local).AddTicks(2160),
                            Summary = "Cool",
                            TemperatureC = -5
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2020, 1, 4, 22, 50, 29, 359, DateTimeKind.Local).AddTicks(2165),
                            Summary = "Bracing",
                            TemperatureC = -17
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2020, 1, 5, 22, 50, 29, 359, DateTimeKind.Local).AddTicks(2168),
                            Summary = "Bracing",
                            TemperatureC = 31
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
